Vivo's translation into Russian
vivo-project/VIVO-languages pull request #104
Opened 2021-10-28 11:02 UTC by litvinovg

This PR adds translations in Russian for VIVO.

2021-11-26 12:04 UTC, chenejac requested changes
@litvinovg, similarly as for your VITRO-language pull request, I have tried to "visually" review that, to check whether something is missing, but I am not a Russian speaker, therefore I didn't check translations.

2021-11-26 12:04 UTC, chenejac commented on ru_RU/webapp/src/main/webapp/i18n/vivo_all_ru_RU.properties
> +year_not_chartered = год (не указан выше)\u0020
The Unicode \u0020 here with a reason?

2021-11-26 20:51 UTC, litvinovg commented on ru_RU/webapp/src/main/webapp/i18n/vivo_all_ru_RU.properties
> +year_not_chartered = год (не указан выше)\u0020
Not this time. Fixed.

2021-11-26 20:52 UTC, litvinovg commented on ru_RU/webapp/src/main/webapp/i18n/vivo_all_ru_RU.properties
> +were = было\u0020
No. Fixed.

2021-11-26 20:52 UTC, litvinovg commented on ru_RU/home/src/main/resources/rdf/i18n/ru_RU/tbox/firsttime/vitroAnnotations_ru_RU.n3
> +              "Starting page number within a continuous page range."@ru-RU .
Fixed

2021-11-26 20:52 UTC, litvinovg commented on ru_RU/home/src/main/resources/rdf/i18n/ru_RU/tbox/firsttime/vitroAnnotations_ru_RU.n3
> +              "A title placed before a person's name."@ru-RU .
Fixed

2021-11-26 21:09 UTC, litvinovg commented on ru_RU/home/src/main/resources/rdf/i18n/ru_RU/tbox/firsttime/initialTBoxAnnotations_ru_RU.nt
> +<http://www.w3.org/2006/vcard/ns#telephone> <http://www.w3.org/2000/01/rdf-schema#label> "Телефон"@ru-RU .
There are both <http://www.w3.org/2006/vcard/ns#telephone> and <http://www.w3.org/2006/vcard/ns#Telephone> in use, so I guess both should be translated.

2021-11-26 21:14 UTC, litvinovg commented on ru_RU/home/src/main/resources/rdf/i18n/ru_RU/tbox/firsttime/vitroAnnotations_ru_RU.n3
> +              "The identification number given to the profile created by a researcher in ResearcherID (https://researcherid.com/)."@ru-RU .
Fixed

2021-11-29 09:41 UTC, chenejac approved these changes

2021-11-30 08:54 UTC, chenejac commented on ru_RU/webapp/src/main/webapp/templates/freemarker/lib/lib-home-page_ru_RU.ftl
> +<#-- $This file is distributed under the terms of the license in LICENSE$ -->
Is this file needed for localization in Russian?

2022-03-24 09:30 UTC, tawahle approved these changes

2022-04-11 12:38 UTC, chenejac approved these changes

2022-04-11 20:48 UTC, merged