Localization of VIVO into Serbian (Latin script)
vivo-project/VIVO-languages pull request #105
Opened 2021-11-02 00:56 UTC by VeljkoMaksimovic

This localization is dependent on changes made to Vitro in this pull request https://github.com/vivo-project/Vitro/pull/250

2021-11-30 08:58 UTC, chenejac requested changes
@VeljkoMaksimovic please, resolve all comments and translate missed properties and files.

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +ingest_menu = Meni za prikupljanje podataka
Meni za unos podataka

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +harvester_location = prikupljač.lokacija
harvester.location

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +harvest_error_instructions_three = Svojsvo unutar runtime.properties fajla pokazuje na direktorijum gde je instaliran Prikupljač.
svojsvo unutar runtime.properties fajla pokazuje na direktorijum gde je instaliran Prikupljač podataka.

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +click_to_harvest = Kliknite na dugme da prikupite informacije iz fajlova.
prikupite podatke

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +#TODO feature= funkcionalnost in this context?
correct

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +create_own_concept = Odaberite ili kreirajte koncept definisan od strane VIVO-a.
koncept u VIVO sistemu.

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +#TODO need context
prisustvovali is fine

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +cannot_find_concept = Ne možete da pronađete koncept koji Vam je potreban? Odaberite ili kreirajte koncept definisan od strane VIVO-a.
Ne možete da pronađete koncept koji Vam je potreban? Kreirajte koncept u VIVO sistemu.

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +#TODO Not sure how to translate initial "ok"
u redu is fine

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +#TODO Need context
correct

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +add_webpage = DOdajte veb stranicu
DOdajte -> Dodajte

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +faculty_of_1000 = Faculty of 1000 Link
Fakultet sa 1000 linkova

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +#TODO Not sure
correct

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +principal_investigator_entry_for = Unos glavnog istraživača za
Unos rukovodioca istraživanja za

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +co_principal_investigator_entry_for = Unos glavnog istraživača za
Unos zamenika rukovodioca istraživanja za

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +start_year_must_precede_end = Godina početka mora biti ranije od godinekraja.
Godina početka mora biti ranije od godine kraja.

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +#TODO Not sure, need context
it is fine

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +proceedings_of = Obrada
Zbornik radova

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +required_with_last_name = Zahtevano uz novo prezime
Potrebno je novo prezime

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +#TODO Not sure, maybe just to translate it as "Knjiga"
Tom is fine

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +select_existing_local_class = Odaberite postojeću klasu iz lokalnog proširenja
Odaberite postojeću klasu iz lokalnog proširenja ontologije

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +problematic_section_error = Greška: problematična sekcija, kao što je gore navedena, je trebalo da budu rešene.
Greška: problematična sekcija, kao što je gore navedena, je trebalo već da bude rešena.

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +check_grants_to_exclude = Štiklirajte one grantove i projekte koje želite da <em>izostavite</em> sa profilne stranice.
Štiklirajte -> Selektujte

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +advisor_capitalized = Savitnik
Savetnik

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +award_or_honor_for = NAgrada ili priznanje za
NAgrada -> Nagrada

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +#TODO conferrer poverilac ili osoba koja uručuje/dodeljuje?
poverilac

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +temporal_graph_drill_up = temporal graph drill up
izrada vremenskog grafikona

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +no_view_link = no view link
nema veze (linka)

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +co_author_s_capitalized = Ko-autoroi
Ko-autori

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +investigator_name = nazim istražitelja
nazim -> naziv

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +#TODO yet to be translated
please translate the following 5 properties

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +advising_relationship = advising relationship
vrsta savetovanja

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +of_pubs = of pubs.
publikacija.

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +level_undefined_error = ENTITY LEVEL UNDEFINED ERROR
please translate

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +drill_down = drill down
izrada

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +none_of_the = Ni njedan
Ni jedan

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +#TODO need context
correct translation

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +create_and_link_unauthorized_for_profile=You do not have permissions to claim for this user
Nemate pravo potvrde za ovog korisnika

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/templates/freemarker/visualization/mapOfScience/mapOfScienceTooltips_sr_RS.ftl
> +<#-- $This file is distributed under the terms of the license in LICENSE$ -->
This document is not translated

2021-11-30 08:58 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/themes/tenderfoot/i18n/all_sr_Latn_RS.properties
> +collapsed_menu_name = Menu
This document is not translated at all

2022-03-30 16:46 UTC, VeljkoMaksimovic commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +award_receipt_name = naziv priznanice za nagradu
Ima svakako više smisla od mog prevoda, ali zar onda ne bi bilo recipient? Možda se misli ovde na potvrdu? Na primer ako potvrda za odrećenu nagradu ima posebno ime? Nisam siguran pošto ne znam u kom kontekstu se koristi

2022-04-05 06:24 UTC, VeljkoMaksimovic commented on sr_Latn_RS/home/src/main/resources/rdf/i18n/sr_Latn_RS/tbox/firsttime/initialTBoxAnnotations_sr_Latn_RS.nt
> +<http://vivoweb.org/ontology/core#pmcid> <http://www.w3.org/2000/01/rdf-schema#label> "Centralni PubMed ID"@sr-Latn-RS .
Translated this document. Left #TODO  comments on ~10 lines I wasnt sure how to translate

2022-04-06 07:24 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +award_receipt_name = naziv priznanice za nagradu
Stavi onda Naziv zapisa o dodeli nagrade. Pogledao sam prevod za nemacki stavio ga na googleTranslate i dobio ovo. Mozda su oni diskutovali to sa nekim. To je najbolje sto mozemo sada. Naravno, ako naknadno ustanovima da ima nesto bolje popravicemo. U ovom fajlu su takodje neki cudni znaci na kraju svakog reda (neko M, vidi na github-u u PR).

2022-04-06 07:27 UTC, chenejac commented on sr_Latn_RS/home/src/main/resources/rdf/i18n/sr_Latn_RS/tbox/firsttime/initialTBoxAnnotations_sr_Latn_RS.nt
> +<http://vivoweb.org/ontology/core#pmcid> <http://www.w3.org/2000/01/rdf-schema#label> "Centralni PubMed ID"@sr-Latn-RS .
I don't see your commit, everything still in English and no TODO comments

2022-04-06 08:08 UTC, chenejac requested changes

2022-04-06 08:08 UTC, chenejac commented on sr_Latn_RS/home/src/main/resources/rdf/i18n/sr_Latn_RS/tbox/firsttime/initialTBoxAnnotations_sr_Latn_RS.nt
> +<http://purl.obolibrary.org/obo/ERO_0000424> <http://www.w3.org/2000/01/rdf-schema#label> "has study population"@sr-Latn-RS .
ovo drugo bolje zvuči

2022-04-06 08:08 UTC, chenejac commented on sr_Latn_RS/home/src/main/resources/rdf/i18n/sr_Latn_RS/tbox/firsttime/initialTBoxAnnotations_sr_Latn_RS.nt
> +<http://purl.obolibrary.org/obo/BFO_0000031> <http://www.w3.org/2000/01/rdf-schema#label> "Generically Dependent Continuant"@sr-Latn-RS .
Uslovni nastavak ili Uslovni produžetak

2022-04-06 08:08 UTC, chenejac commented on sr_Latn_RS/home/src/main/resources/rdf/i18n/sr_Latn_RS/tbox/firsttime/initialTBoxAnnotations_sr_Latn_RS.nt
> +<http://vivoweb.org/ontology/core#OutreachProviderRole> <http://www.w3.org/2000/01/rdf-schema#label> "Outreach Provider Role"@sr-Latn-RS .
Uloga pružaoca usluga

2022-04-06 08:08 UTC, chenejac commented on sr_Latn_RS/home/src/main/resources/rdf/i18n/sr_Latn_RS/tbox/firsttime/initialTBoxAnnotations_sr_Latn_RS.nt
> +<http://purl.org/ontology/bibo/coden> <http://www.w3.org/2000/01/rdf-schema#label> "coden"@sr-Latn-RS .
CODEN (to je valjda ovo - https://en.wikipedia.org/wiki/CODEN)

2022-04-06 08:08 UTC, chenejac commented on sr_Latn_RS/home/src/main/resources/rdf/i18n/sr_Latn_RS/tbox/firsttime/initialTBoxAnnotations_sr_Latn_RS.nt
> +<http://purl.org/dc/terms/> <http://www.w3.org/2000/01/rdf-schema#label> "Dublin Core Terms"@sr-Latn-RS .
Dublin Core termovi

2022-04-06 14:06 UTC, lidijaivanovic requested changes
@VeljkoMaksimovic please see my comments and try to address some of them.

2022-04-06 14:47 UTC, VeljkoMaksimovic commented on sr_Latn_RS/home/src/main/resources/rdf/i18n/sr_Latn_RS/tbox/firsttime/initialTBoxAnnotations_sr_Latn_RS.nt
> +<http://aims.fao.org/aos/geopolitical.owl#nationalityFR> <http://www.w3.org/2000/01/rdf-schema#label> "nacionalnostFR"@sr-Latn-RS .
Yes. The original value was "nationalityFR". Not sure if this should be interpreted as the word "nationality" in French, or as someone With French nationality

2022-04-08 11:23 UTC, litvinovg commented
Should freemarker template filenames also have _sr_Latn_RS suffix instead of _sr_RS ?

2022-04-20 01:36 UTC, VeljkoMaksimovic commented
@litvinovg .ftl templates were working fine with sr_RS, just finished testing them, but you are right, it is better to be more specific with the script. All of those files are now renamed to end with sr_Latn_RS

2022-04-20 07:34 UTC, chenejac approved these changes

2022-04-21 13:16 UTC, merged