[ i18n ] Added translation key vis_records_start_end_of_total
vivo-project/VIVO-languages pull request #119
Opened 2022-11-11 13:41 UTC by litvinovg

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues)**: (please link to issue)
Companion VIVO PR
# What's new?
New translation key vis_records_start_end_of_total for list of publications at /vis/publication-graph page

# Interested parties
@hauschke 
@chenejac

2022-11-11 13:45 UTC, chenejac requested changes

2022-11-11 13:45 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/vivo_all_sr_Latn_RS.properties
> +vis_records_start_end_of_total = Records _START_ - _END_ of _TOTAL_
```suggestion
vis_records_start_end_of_total = Zapisi _START_ - _END_ od ukupno _TOTAL_ 
```

2022-11-11 13:51 UTC, bkampe requested changes

2022-11-11 13:51 UTC, bkampe commented on de_DE/webapp/src/main/webapp/i18n/vivo_all_de_DE.properties
> +vis_records_start_end_of_total = Records _START_ - _END_ of _TOTAL_
```suggestion
vis_records_start_end_of_total = Datensatz _START_ - _END_ von _TOTAL_ 
```

2022-11-11 14:12 UTC, hauschke commented
@bkampe Maybe "Eintrag" instead of "Datensatz"? 

It's been used in the temporal graph visualization:

![grafik](https://user-images.githubusercontent.com/1275231/201357746-80d9dacd-bf3b-4391-bd6c-cb9110507b5d.png)

2022-11-11 14:27 UTC, AnnaGuillaumet commented
Registros 

(normally the word Registry is not usually used, only the numbers appear, but the translation would be, as above: Registros)

2022-11-11 14:36 UTC, michel-heon commented on en_CA/webapp/src/main/webapp/i18n/vivo_all_en_CA.properties
>  vis_tools_note_two = To this end we have devised a caching solution which will retain information about the hierarchy of organizations -- namely, which publications are attributed to which organizati
```suggestion
vis_tools_note_two = À cette fin, nous avons conçu une solution de mise en cache qui conservera les informations sur la hiérarchie des organisations ( à savoir, quelles publications sont attribuées à quelles organisations ),  en stockant le modèle RDF.

```

2022-11-11 14:36 UTC, michel-heon commented on en_CA/webapp/src/main/webapp/i18n/vivo_all_en_CA.properties
>  vis_tools_note_three = We're currently caching these models in memory.  The cache is built (only once) on the first user request after a server restart.  Because of this, the same model will be serve
```suggestion
vis_tools_note_three = Nous mettons actuellement ces modèles dans la mémoire tampon.  La mémoire tampon est construit (une seule fois) lors de la première demande de l'utilisateur après un redémarrage du serveur.  De ce fait, le même modèle sera utilisé jusqu'au prochain redémarrage. Cela signifie que les données de ces modèles peuvent devenir périmées en fonction de la date de leur dernière création. Cela fonctionne assez bien pour l'instant. Dans les prochaines versions, nous améliorerons cette solution afin que les modèles soient stockés sur le disque et mis à jour périodiquement.
```

2022-11-11 14:36 UTC, michel-heon commented on en_CA/webapp/src/main/webapp/i18n/vivo_all_en_CA.properties
>  vis_tools_note_four = The models are refreshed each time the server restarts.  Since this is not generally practical on production instances, administrators can instead use the "refresh cache" link a
```suggestion
vis_tools_note_four = Les modèles sont rafraîchis chaque fois que le serveur redémarre.  Comme ce n'est généralement pas utile sur les instances de production, les administrateurs peuvent utiliser le lien "refresh cache" ci-dessus pour effectuer cette opération sans redémarrage.


```

2022-11-11 14:36 UTC, michel-heon commented on en_CA/webapp/src/main/webapp/i18n/vivo_all_en_CA.properties
>  capability_map=Capability Map
```suggestion
capability_map=Cartographie des expertises

```

2022-11-11 14:36 UTC, michel-heon commented on en_CA/webapp/src/main/webapp/i18n/vivo_all_en_CA.properties
>  term_capitalized=Term
```suggestion
term_capitalized=Terme

```

2022-11-11 14:36 UTC, michel-heon commented on en_CA/webapp/src/main/webapp/i18n/vivo_all_en_CA.properties
> +vis_records_start_end_of_total = Records _START_ - _END_ of _TOTAL_
```suggestion
vis_records_start_end_of_total = Enregistrement _START_ - _END_ de _TOTAL_ 

```

2022-11-11 14:42 UTC, litvinovg commented on en_CA/webapp/src/main/webapp/i18n/vivo_all_en_CA.properties
>  vis_tools_note_three = We're currently caching these models in memory.  The cache is built (only once) on the first user request after a server restart.  Because of this, the same model will be serve
That was en_CA file

2022-11-14 08:02 UTC, bkampe approved these changes

2022-11-17 09:35 UTC, chenejac approved these changes

2022-11-17 09:35 UTC, merged