Change one label in initialTBoxAnnotations_fr_CA.nt
vivo-project/VIVO-languages pull request #99
Opened 2021-09-08 10:48 UTC by michel-heon

in file en_CA/home/src/main/resources/rdf/i18n/en_CA/tbox/firsttime/initialTBoxAnnotations_en_CA.nt
Change 'ExpertisesLivres' to 'Expertises'

This change affects the title of the expertise presentation in the user interface.
In French, the wording 'ExpertisesLivres' means nothing

2021-12-10 11:45 UTC, chenejac reviewed
We need to merge only the second commit (out of three) https://github.com/vivo-project/VIVO-languages/pull/99/commits/9c571f1e1d2c0baede01dd0f16e56578958d5b22, which is change of just one triple. Is there some easier way than this one https://code-maven.com/merge-one-commit-from-a-pull-request?

2021-12-10 11:45 UTC, chenejac commented on fr_CA/home/src/main/resources/rdf/i18n/fr_CA/tbox/firsttime/initialTBoxAnnotations_fr_CA.nt
> +<http://www.w3.org/2004/02/skos/core#Concept> <http://www.w3.org/2000/01/rdf-schema#label> "Expertises"@fr-CA .
I suppose this is ok, I am not a French speaker.

2021-12-18 06:35 UTC, wwelling requested changes
First off, not sure why the heck there are so many pom files with the same thing in them. Maybe it is unavoidable. I suspect not though. Worth thinking about to reduce all pom files to bare minimum. I would think adding parent pom or hoisting to an existing parent pom. Anyhow, since we have to deal with these nonsensical build files for now, can we keep them generic as possible and try not to muddy up the commit history. Just kidding. I agree with Dragan, only the “language file” needs changed in this PR. Please update.

2021-12-18 06:38 UTC, wwelling commented
I would say easiest way to recreate this PR would be to reset to head, make change in one file, commit, and force push.

2022-08-25 14:45 UTC, closed without merging